import {
  Activity,
  Anchor,
  Award,
  BarChart3,
  Bell,
  Bitcoin,
  Bookmark,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  Car,
  CheckCircle2,
  Clock,
  Code,
  Coins,
  Compass,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Dumbbell,
  Factory,
  FileText,
  Flag,
  Flame,
  Gauge,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Leaf,
  Lightbulb,
  type LucideIcon,
  MapPin,
  Megaphone,
  MessageCircle,
  Music,
  Network,
  Package,
  Palette,
  PartyPopper,
  PiggyBank,
  Plane,
  Rocket,
  Scale,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Wallet,
  Wrench,
  Zap,
} from 'lucide-react'

export interface IconEntry {
  /** Canonical stored value — the Lucide component name. */
  name: string
  Icon: LucideIcon
  /** Human-friendly label shown in the picker. */
  label: string
  /** Terms used for keyword + semantic matching. */
  keywords: string[]
}

/**
 * Curated icon set used by the icon picker and anywhere a user-chosen icon is
 * rendered. The stored value is the icon's `name` (the Lucide component name).
 */
export const ICON_LIBRARY: IconEntry[] = [
  {
    name: 'DollarSign',
    Icon: DollarSign,
    label: 'Money',
    keywords: [
      'money',
      'cash',
      'dollar',
      'income',
      'salary',
      'revenue',
      'price',
      'cost',
      'finance',
      'fund',
    ],
  },
  {
    name: 'Coins',
    Icon: Coins,
    label: 'Coins',
    keywords: [
      'coins',
      'savings',
      'capital',
      'currency',
      'wealth',
      'budget',
      'money',
    ],
  },
  {
    name: 'Wallet',
    Icon: Wallet,
    label: 'Wallet',
    keywords: [
      'wallet',
      'spending',
      'budget',
      'expense',
      'pocket',
      'money',
      'cash',
    ],
  },
  {
    name: 'PiggyBank',
    Icon: PiggyBank,
    label: 'Savings',
    keywords: [
      'savings',
      'save',
      'piggy bank',
      'deposit',
      'nest egg',
      'retirement',
      'money',
    ],
  },
  {
    name: 'CreditCard',
    Icon: CreditCard,
    label: 'Card',
    keywords: [
      'credit card',
      'payment',
      'debit',
      'pay',
      'billing',
      'purchase',
      'money',
    ],
  },
  {
    name: 'Bitcoin',
    Icon: Bitcoin,
    label: 'Crypto',
    keywords: [
      'bitcoin',
      'crypto',
      'cryptocurrency',
      'blockchain',
      'digital currency',
      'token',
    ],
  },
  {
    name: 'TrendingUp',
    Icon: TrendingUp,
    label: 'Growth',
    keywords: [
      'growth',
      'trend',
      'increase',
      'investment',
      'returns',
      'profit',
      'gain',
      'stock',
      'market',
    ],
  },
  {
    name: 'BarChart3',
    Icon: BarChart3,
    label: 'Analytics',
    keywords: [
      'chart',
      'analytics',
      'metrics',
      'data',
      'stats',
      'statistics',
      'report',
      'dimension',
      'measure',
    ],
  },
  {
    name: 'Gauge',
    Icon: Gauge,
    label: 'Gauge',
    keywords: [
      'gauge',
      'meter',
      'level',
      'score',
      'readiness',
      'progress',
      'performance',
      'speed',
    ],
  },
  {
    name: 'Clock',
    Icon: Clock,
    label: 'Time',
    keywords: [
      'time',
      'hours',
      'clock',
      'duration',
      'schedule',
      'deadline',
      'minutes',
    ],
  },
  {
    name: 'Calendar',
    Icon: Calendar,
    label: 'Calendar',
    keywords: [
      'calendar',
      'date',
      'schedule',
      'event',
      'appointment',
      'plan',
      'meeting',
    ],
  },
  {
    name: 'Briefcase',
    Icon: Briefcase,
    label: 'Work',
    keywords: [
      'work',
      'job',
      'career',
      'employment',
      'business',
      'office',
      'professional',
    ],
  },
  {
    name: 'GraduationCap',
    Icon: GraduationCap,
    label: 'Education',
    keywords: [
      'education',
      'school',
      'degree',
      'study',
      'learning',
      'university',
      'graduate',
      'academic',
    ],
  },
  {
    name: 'BookOpen',
    Icon: BookOpen,
    label: 'Knowledge',
    keywords: [
      'book',
      'reading',
      'knowledge',
      'learning',
      'course',
      'study',
      'literacy',
      'research',
    ],
  },
  {
    name: 'Brain',
    Icon: Brain,
    label: 'Skill',
    keywords: [
      'brain',
      'skill',
      'mind',
      'intelligence',
      'knowledge',
      'thinking',
      'mental',
      'expertise',
      'cognition',
    ],
  },
  {
    name: 'Lightbulb',
    Icon: Lightbulb,
    label: 'Idea',
    keywords: [
      'idea',
      'lightbulb',
      'innovation',
      'insight',
      'creativity',
      'inspiration',
      'concept',
    ],
  },
  {
    name: 'Code',
    Icon: Code,
    label: 'Code',
    keywords: [
      'code',
      'programming',
      'software',
      'development',
      'engineering',
      'tech',
      'developer',
    ],
  },
  {
    name: 'Rocket',
    Icon: Rocket,
    label: 'Launch',
    keywords: [
      'rocket',
      'launch',
      'startup',
      'business',
      'growth',
      'ship',
      'venture',
      'accelerate',
    ],
  },
  {
    name: 'Target',
    Icon: Target,
    label: 'Goal',
    keywords: [
      'target',
      'goal',
      'objective',
      'aim',
      'focus',
      'milestone',
      'mission',
    ],
  },
  {
    name: 'Flag',
    Icon: Flag,
    label: 'Milestone',
    keywords: ['flag', 'milestone', 'checkpoint', 'marker', 'goal', 'finish'],
  },
  {
    name: 'Trophy',
    Icon: Trophy,
    label: 'Achievement',
    keywords: [
      'trophy',
      'win',
      'achievement',
      'award',
      'success',
      'champion',
      'victory',
    ],
  },
  {
    name: 'Award',
    Icon: Award,
    label: 'Award',
    keywords: [
      'award',
      'medal',
      'recognition',
      'honor',
      'prize',
      'certificate',
      'accomplishment',
    ],
  },
  {
    name: 'Crown',
    Icon: Crown,
    label: 'Leadership',
    keywords: [
      'crown',
      'leadership',
      'authority',
      'power',
      'control',
      'king',
      'rule',
      'dominance',
    ],
  },
  {
    name: 'Star',
    Icon: Star,
    label: 'Star',
    keywords: [
      'star',
      'favorite',
      'rating',
      'quality',
      'priority',
      'highlight',
      'reputation',
    ],
  },
  {
    name: 'Sparkles',
    Icon: Sparkles,
    label: 'Sparkle',
    keywords: ['sparkles', 'magic', 'new', 'special', 'shine', 'ai', 'enhance'],
  },
  {
    name: 'Users',
    Icon: Users,
    label: 'People',
    keywords: [
      'people',
      'users',
      'team',
      'group',
      'social',
      'community',
      'network',
      'audience',
    ],
  },
  {
    name: 'Handshake',
    Icon: Handshake,
    label: 'Partnership',
    keywords: [
      'handshake',
      'partnership',
      'deal',
      'agreement',
      'network',
      'relationship',
      'collaboration',
      'trust',
    ],
  },
  {
    name: 'Network',
    Icon: Network,
    label: 'Network',
    keywords: [
      'network',
      'connection',
      'nodes',
      'links',
      'relationship',
      'graph',
      'web',
    ],
  },
  {
    name: 'MessageCircle',
    Icon: MessageCircle,
    label: 'Communication',
    keywords: [
      'message',
      'chat',
      'communication',
      'talk',
      'conversation',
      'feedback',
      'comment',
    ],
  },
  {
    name: 'Megaphone',
    Icon: Megaphone,
    label: 'Marketing',
    keywords: [
      'megaphone',
      'marketing',
      'announce',
      'promotion',
      'advertising',
      'broadcast',
      'influence',
    ],
  },
  {
    name: 'Heart',
    Icon: Heart,
    label: 'Relationship',
    keywords: [
      'heart',
      'love',
      'relationship',
      'family',
      'care',
      'passion',
      'wellbeing',
    ],
  },
  {
    name: 'HeartPulse',
    Icon: HeartPulse,
    label: 'Health',
    keywords: [
      'health',
      'pulse',
      'medical',
      'fitness',
      'wellness',
      'heartbeat',
      'vitals',
    ],
  },
  {
    name: 'Dumbbell',
    Icon: Dumbbell,
    label: 'Fitness',
    keywords: [
      'dumbbell',
      'fitness',
      'gym',
      'exercise',
      'workout',
      'strength',
      'training',
      'physical',
    ],
  },
  {
    name: 'Activity',
    Icon: Activity,
    label: 'Activity',
    keywords: [
      'activity',
      'energy',
      'movement',
      'health',
      'pulse',
      'action',
      'momentum',
    ],
  },
  {
    name: 'Zap',
    Icon: Zap,
    label: 'Energy',
    keywords: [
      'zap',
      'energy',
      'power',
      'electric',
      'fast',
      'boost',
      'spark',
      'intensity',
    ],
  },
  {
    name: 'Flame',
    Icon: Flame,
    label: 'Momentum',
    keywords: [
      'flame',
      'fire',
      'streak',
      'momentum',
      'hot',
      'passion',
      'burn',
      'drive',
    ],
  },
  {
    name: 'Leaf',
    Icon: Leaf,
    label: 'Sustainability',
    keywords: [
      'leaf',
      'nature',
      'growth',
      'sustainability',
      'eco',
      'organic',
      'green',
      'environment',
    ],
  },
  {
    name: 'Home',
    Icon: Home,
    label: 'Home',
    keywords: [
      'home',
      'house',
      'property',
      'real estate',
      'asset',
      'living',
      'family',
    ],
  },
  {
    name: 'Building2',
    Icon: Building2,
    label: 'Company',
    keywords: [
      'building',
      'company',
      'organization',
      'corporate',
      'office',
      'enterprise',
      'institution',
    ],
  },
  {
    name: 'Landmark',
    Icon: Landmark,
    label: 'Institution',
    keywords: [
      'landmark',
      'institution',
      'government',
      'bank',
      'organization',
      'civic',
      'authority',
    ],
  },
  {
    name: 'Factory',
    Icon: Factory,
    label: 'Production',
    keywords: [
      'factory',
      'production',
      'manufacturing',
      'industry',
      'output',
      'operations',
    ],
  },
  {
    name: 'ShoppingCart',
    Icon: ShoppingCart,
    label: 'Commerce',
    keywords: [
      'shopping',
      'cart',
      'commerce',
      'retail',
      'sales',
      'buy',
      'ecommerce',
      'store',
    ],
  },
  {
    name: 'Package',
    Icon: Package,
    label: 'Product',
    keywords: [
      'package',
      'product',
      'box',
      'shipping',
      'delivery',
      'inventory',
      'asset',
      'other',
    ],
  },
  {
    name: 'Database',
    Icon: Database,
    label: 'Data',
    keywords: [
      'database',
      'data',
      'storage',
      'records',
      'information',
      'server',
      'backend',
    ],
  },
  {
    name: 'Globe',
    Icon: Globe,
    label: 'Global',
    keywords: [
      'globe',
      'world',
      'global',
      'international',
      'web',
      'internet',
      'reach',
      'platform',
    ],
  },
  {
    name: 'Plane',
    Icon: Plane,
    label: 'Travel',
    keywords: [
      'plane',
      'travel',
      'flight',
      'trip',
      'vacation',
      'journey',
      'mobility',
    ],
  },
  {
    name: 'Car',
    Icon: Car,
    label: 'Vehicle',
    keywords: [
      'car',
      'vehicle',
      'transport',
      'drive',
      'commute',
      'mobility',
      'auto',
    ],
  },
  {
    name: 'MapPin',
    Icon: MapPin,
    label: 'Location',
    keywords: [
      'location',
      'place',
      'map',
      'pin',
      'address',
      'geography',
      'position',
    ],
  },
  {
    name: 'Compass',
    Icon: Compass,
    label: 'Direction',
    keywords: [
      'compass',
      'direction',
      'navigation',
      'strategy',
      'guidance',
      'explore',
      'orientation',
    ],
  },
  {
    name: 'Anchor',
    Icon: Anchor,
    label: 'Stability',
    keywords: [
      'anchor',
      'stability',
      'foundation',
      'security',
      'base',
      'grounding',
      'reliable',
    ],
  },
  {
    name: 'Shield',
    Icon: Shield,
    label: 'Protection',
    keywords: [
      'shield',
      'protection',
      'security',
      'safety',
      'defense',
      'insurance',
      'guard',
      'risk',
    ],
  },
  {
    name: 'Scale',
    Icon: Scale,
    label: 'Balance',
    keywords: [
      'scale',
      'balance',
      'justice',
      'law',
      'fairness',
      'legal',
      'equity',
      'weigh',
    ],
  },
  {
    name: 'Gem',
    Icon: Gem,
    label: 'Value',
    keywords: [
      'gem',
      'diamond',
      'value',
      'precious',
      'premium',
      'asset',
      'wealth',
      'quality',
    ],
  },
  {
    name: 'Palette',
    Icon: Palette,
    label: 'Creative',
    keywords: [
      'palette',
      'art',
      'creative',
      'design',
      'color',
      'painting',
      'aesthetic',
    ],
  },
  {
    name: 'Music',
    Icon: Music,
    label: 'Music',
    keywords: ['music', 'audio', 'sound', 'song', 'melody', 'entertainment'],
  },
  {
    name: 'PartyPopper',
    Icon: PartyPopper,
    label: 'Event',
    keywords: [
      'party',
      'event',
      'celebration',
      'festival',
      'gathering',
      'series',
      'launch',
    ],
  },
  {
    name: 'Gift',
    Icon: Gift,
    label: 'Reward',
    keywords: [
      'gift',
      'reward',
      'present',
      'bonus',
      'benefit',
      'perk',
      'giving',
    ],
  },
  {
    name: 'Wrench',
    Icon: Wrench,
    label: 'Tools',
    keywords: [
      'wrench',
      'tools',
      'maintenance',
      'repair',
      'build',
      'fix',
      'utility',
    ],
  },
  {
    name: 'FileText',
    Icon: FileText,
    label: 'Document',
    keywords: [
      'file',
      'document',
      'text',
      'paper',
      'report',
      'note',
      'content',
      'platform',
    ],
  },
  {
    name: 'Bookmark',
    Icon: Bookmark,
    label: 'Bookmark',
    keywords: ['bookmark', 'save', 'mark', 'reference', 'tag', 'remember'],
  },
  {
    name: 'Bell',
    Icon: Bell,
    label: 'Reminder',
    keywords: ['bell', 'notification', 'reminder', 'alert', 'ring', 'notice'],
  },
  {
    name: 'CheckCircle2',
    Icon: CheckCircle2,
    label: 'Done',
    keywords: [
      'check',
      'done',
      'complete',
      'success',
      'verified',
      'approved',
      'finished',
    ],
  },
]

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map((entry) => [entry.name, entry.Icon])
)

/**
 * Renders a stored icon by name. Falls back to rendering the raw value as text
 * so legacy emoji values (saved before the icon picker existed) still display.
 */
export function AppIcon({
  name,
  className,
}: {
  name?: string | null
  className?: string
}) {
  if (!name) return null
  const Icon = ICON_MAP[name]
  if (Icon) return <Icon className={className} aria-hidden="true" />
  return (
    <span className={className} aria-hidden="true">
      {name}
    </span>
  )
}

const VEHICLE_TYPE_ICON: Record<string, LucideIcon> = {
  EDUCATION: GraduationCap,
  EMPLOYMENT: Briefcase,
  BUSINESS: Rocket,
  ASSET: Home,
  PLATFORM: FileText,
  NETWORK: Handshake,
  ORGANIZATION: Landmark,
  EVENT_SERIES: PartyPopper,
  SKILL: Brain,
  OTHER: Package,
}

export function VehicleTypeIcon({
  type,
  className,
}: {
  type: string
  className?: string
}) {
  const Icon = VEHICLE_TYPE_ICON[type] ?? Package
  return <Icon className={className} aria-hidden="true" />
}
